plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.primerproyectoandroid'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.primerproyectoandroid'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}
